name: Déploiement dev Vite ma dose

on:
  push:
    branches:
      - dev

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v3.x
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14.12"
      - run: npm ci
      - run: npm run build-dev
        env:
          BASE_URL:  "${{ env.GITHUB_REF_SLUG }}/"
      - name: rsync deployments
        uses: burnett01/rsync-deployments@4.1
        with:
          switches: -avz --delete --exclude ".git*"
          path: ./dist/
          remote_path: ${{ secrets.DEPLOY_PATH_DEV }}${{ env.GITHUB_REF_SLUG }}
          remote_host: ${{ secrets.DEPLOY_IP }}
          remote_user: ubuntu
          remote_key: ${{ secrets.DEPLOY_KEY }}
